### Fractal OAuth2 - Get Redirect URL for Browser

GET http://localhost:8989/createRedirect HTTP/1.1

### Callback for Webhook - Change user_id to result of Redirect call

POST http://localhost:8989/callback HTTP/1.1
content-type: application/json

{
    "type": "verification_approved",
    "data": {
        "level": "v1",
        "user_id": "982d7598-72d8-432b-8de6-f3330474d8cb",
        "timestamp": "2021-09-02T13:35:35Z"
    }
}